export enum Privilege {
  USER_VIEW = 'USER_VIEW',
  USER_EDIT = 'USER_EDIT',
  USER_CREATE = 'USER_CREATE',
  USER_DELETE = 'USER_DELETE',
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_EDIT = 'ROLE_EDIT',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_DELETE = 'ROLE_DELETE',
  NONE = 'NONE'
}
